default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: rental_development

test:
  <<: *default
  database: rental_test

production:
  <<: *default
  database: rental_production
